version: "3.9"

services:
  openvpn:
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - ./vpn/:/vpn
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    ports:
      - "1080:1080"
      - "9001:9001"

  socks:
    image: serjs/go-socks5-proxy
    depends_on:
      - openvpn
    environment:
      - PROXY_USER=${PROXY_USER}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
    network_mode: "service:openvpn"
    stdin_open: true
    tty: true

  socat:
    image: alpine/socat
    depends_on:
      - openvpn
    command: "-d -d TCP-LISTEN:9001 STDOUT"
    network_mode: "service:openvpn"
    stdin_open: true
    tty: true
